### ISSUE TITLE
Crash when previous cell has unsupported data

### ISSUE THREAD

**Issue by rhcarvalho** [livebook-dev/kino_explorer#104]
I'm unable to use the smart cell because my notebook has MongoDB.ObjectId values.

```
    {:kino_explorer, "~> 0.1.9"},
    {:explorer, "~> 0.7.0"}
```

```
19:11:33.878 [error] GenServer #PID<0.2447.0> terminating
** (ArgumentError) cannot create series "_id": unsupported datatype: #BSON.ObjectId<633dde08069d480008ba9b9f>
    (explorer 0.7.0) lib/explorer/polars_backend/data_frame.ex:572: Explorer.PolarsBackend.DataFrame.series_from_list!/3
    (explorer 0.7.0) lib/explorer/polars_backend/data_frame.ex:522: anonymous fn/3 in Explorer.PolarsBackend.DataFrame.from_tabular/2
    (elixir 1.15.2) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (explorer 0.7.0) lib/explorer/polars_backend/data_frame.ex:516: Explorer.PolarsBackend.DataFrame.from_tabular/2
    (kino_explorer 0.1.10) lib/kino_explorer/data_transform_cell.ex:846: KinoExplorer.DataTransformCell.update_data_options/3
    (kino_explorer 0.1.10) lib/kino_explorer/data_transform_cell.ex:337: KinoExplorer.DataTransformCell.updates_for_data_frame/2
    (kino_explorer 0.1.10) lib/kino_explorer/data_transform_cell.ex:189: KinoExplorer.DataTransformCell.handle_info/2
    (kino 0.10.0) lib/kino/js/live/server.ex:134: Kino.JS.Live.Server.call_handle_info_fallback/3
Last message: {:scan_binding_result, [videos: [%{"_id" => #BSON.ObjectId<633de7ac069d480008ba9bb3>, ... (truncated)
```

> The Smart cell crashed unexpectedly, this is most likely a bug.
> Restart Smart cell

The previous cell also has a valid Explorer.DataFrame towards the end, but, since the Smart Cell crashed, I cannot use it.

**Comment by cristineguadelupe** [comment]
Fixed in #106
